---
  - name: Create group role & GID {{ guser }}
    group: name={{ guser }} state=present gid={{ guser_guid }}

  - name: Create user role & UID
    user: home={{ guser_home }} name={{ guser }} state=present shell=/bin/bash uid={{ guser_guid }} group={{ guser }}

  - name: SSH key deployment for galaxy user
    authorized_key: user={{ guser }} key="{{ item }}"
    with_file:
      - ~/.ssh/id_rsa.pub

  - name: Update mode to the project directory
    file: group={{ guser }} owner={{ guser }} mode=755 state=directory path={{ guser_home }}
