---

  - name: Create group role & GID {{ user }}
    group: name={{ user }} state=present gid={{ user_guid }}

  - name: Create user role & UID
    user: home={{ user_home }} name={{ user }} state=present shell=/bin/bash uid={{ user_guid }} group={{ user }}

  - name: SSH key deployment for galaxy user
    authorized_key: user={{ user }} key="{{ item }}"
    with_file:
      - ~/.ssh/id_rsa.pub

  - name: Update mode to the project directory
    file: group={{ user }} owner={{ user }} mode=755 state=directory path={{ user_home }}
